services:
  db:
    image: postgres:16
    container_name: freelaflow-db
    environment:
      POSTGRES_USER: freela
      POSTGRES_PASSWORD: freela123
      POSTGRES_DB: freelaflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
